# Generated by Django 3.2.9 on 2022-04-16 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20220416_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='duration',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
