# Generated by Django 3.2.9 on 2022-04-16 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_project_project_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='facebook_profile',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='github_profile',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='hashnode_profile',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='instagram_profile',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='linkedin_profile',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='medium_profile',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='youtube_profile',
            field=models.URLField(blank=True, null=True),
        ),
    ]
