# Generated by Django 3.2.9 on 2022-04-18 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20220416_2325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='last_name',
            new_name='subject',
        ),
    ]
