# Generated by Django 3.2.9 on 2022-04-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20220403_1505'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postreview',
            old_name='project',
            new_name='post',
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10),
        ),
    ]
