# Generated by Django 3.2.9 on 2022-04-12 06:42

import blog.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0003_auto_20220405_1248"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PostReview",
            new_name="Review",
        ),
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=blog.models.upload_to,
                verbose_name="Image",
            ),
        ),
    ]
