# Generated by Django 3.2.9 on 2022-04-12 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20220412_0742'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='description',
            new_name='review',
        ),
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
    ]
