# Generated by Django 3.2.14 on 2022-09-12 12:45

import authentication.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='store/images', validators=[authentication.validators.validate_file_size]),
        ),
    ]
